"""Generate the explicit native whitelist from the reviewed engine baseline snapshot.
Changing designer-catalog.json alone still cannot admit arbitrary actor/template combinations.
"""
import json
from pathlib import Path
from stock_combat_expansion import ROWS, key, gear, motor, generator, carrier, prerequisites

REPO = Path(__file__).resolve().parents[2]
TARGET = REPO / 'OpenRA.Mods.CA/Modular/StockCombatAssemblies.cs'


def render():
    lines = ['// Generated by tools/modular/generate_stock_combat_bindings.py from reviewed stock-combat-baselines.json.',
        'using System.Collections.Generic;', '', 'namespace OpenRA.Mods.CA.Modular', '{',
        '\tpublic sealed partial class CustomFactionDesign', '\t{',
        '\t\tstatic CustomVehicleAssembly StockAssembly(string hull, string actor, string faction, string gear, string motor, string generator, string armor, string carrier, string prerequisites, bool hover)',
        '\t\t{',
        '\t\t\tvar assembly = new CustomVehicleAssembly(hull, actor, actor.ToLowerInvariant(), null, new[] { gear }, new[] { motor }, armor,',
        '\t\t\t\tcarrier, "original-armament", new[] { "integral-stores" }, new Dictionary<string, string>())',
        '\t\t\t{',
        '\t\t\t\tFaction = faction, PreserveWeaponTemplates = true, PreserveActorGraphics = true, InheritStockWeapons = true,',
        '\t\t\t\tStockPrerequisites = prerequisites, NativeHover = hover,',
        '\t\t\t\tSummary = carrier == "superheavy-bunker" ? "Battle Fortress + Bunker Module: originale Besatzung, Schiessscharten, MG/Flak und Bunkergrafik." : "Originale Kampfgruppe: Waffen/Spezialfunktionen am Chassis gebunden und im Preis enthalten."',
        '\t\t\t};',
        '\t\t\tassembly.Choices["generator"] = new[] { generator };',
        '\t\t\treturn assembly;', '\t\t}', '',
        '\t\tstatic CustomVehicleAssembly[] CreateStockCombatAssemblies() => new[]', '\t\t{']
    q = lambda x: json.dumps(x, ensure_ascii=True)
    for r in ROWS:
        args = [key(r)+'-hull', r['actor'], r['faction'], gear(r), motor(r), generator(r), r['armor'].lower(), carrier(r), prerequisites(r)]
        lines.append('\t\t\tStockAssembly(' + ', '.join(map(q, args)) + ', ' + str(r['locomotor'] in ('hover','lighthover')).lower() + '),')
    return '\n'.join(lines + ['\t\t};', '\t}', '}', ''])


if __name__ == '__main__':
    TARGET.write_text(render(), encoding='utf-8')
    print(TARGET)
