using System;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

namespace OpenRA.Mods.CA.UtilityCommands
{
	sealed class RubberduckClosedCliffArtCommand : IUtilityCommand
	{
		string IUtilityCommand.Name => "--rubberduck-closed-cliff-art";
		bool IUtilityCommand.ValidateArguments(string[] args) => args.Length == 3;
		[Desc("SOURCE OUTPUT", "Export the fitted closed-cliff vocabulary, rules, sequences and provenance without modifying originals.")]
		void IUtilityCommand.Run(Utility utility, string[] args)
		{
			var source = Path.GetFullPath(args[1]).TrimEnd(Path.DirectorySeparatorChar);
			var output = Path.GetFullPath(args[2]).TrimEnd(Path.DirectorySeparatorChar);
			if (output.Equals(source, StringComparison.OrdinalIgnoreCase) || output.StartsWith(source + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase))
				throw new ArgumentException("Derived artwork cannot be written into the immutable source tree.");
			Directory.CreateDirectory(output);
			var command = (IUtilityCommand)new RubberduckClosedPlateauTestCommand();
			var slots = new[] { 0, 1, 2, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 18, 20, 22, 24, 26, 28, 30, 100, 105 };
			foreach (var notch in new[] { -1, 0, 1, 2, 3 })
				command.Run(utility, new[] { "--rubberduck-closed-plateau-test", source, Path.Combine(output, "recipe-" + notch), notch.ToString(System.Globalization.CultureInfo.InvariantCulture) });
			foreach (var direction in new[] { 2, 3 })
				command.Run(utility, new[] { "--rubberduck-closed-plateau-test", source, Path.Combine(output, "mouth-" + direction), "-1", "ramp=true", "direction=" + direction });
			var rules = new StringBuilder(); var sequences = new StringBuilder();
			var provenance = new StringBuilder("Fitted height-four derivatives, not unchanged original sprites. Generated by --rubberduck-closed-cliff-art.\nSide pieces use connected-matte reconstruction; front-mouth pieces 100/105 use projected end planes with nearest opaque row sampling and one-pixel opaque matte-fringe reconstruction. No terrain/collision modification. Recipes are retained beside the export.\n");
			foreach (var file in new[] { "grassland_1x1.png", "grass_cliff_trans.png" })
				provenance.AppendLine(file + " SHA256 " + Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(Path.Combine(source, "grassland", file)))));
			foreach (var slot in slots)
			{
				var candidates = Directory.GetFiles(output, $"height4-{slot}.png", SearchOption.AllDirectories);
				if (candidates.Length == 0) throw new InvalidDataException("Missing cliff slot " + slot);
				var bytes = File.ReadAllBytes(candidates[0]);
				if (candidates.Any(f => !File.ReadAllBytes(f).SequenceEqual(bytes))) throw new InvalidDataException("Inconsistent cliff recipe " + slot);
				var filename = $"closed-cliff-{slot}.png";
				File.WriteAllBytes(Path.Combine(output, filename), bytes);
				provenance.AppendLine(filename + " SHA256 " + Convert.ToHexString(SHA256.HashData(bytes)));
				rules.AppendLine($"terrain.rubberduck.closedcliff{slot}:\n\tInherits: ^RubberduckTerrainDecoration\n\t-WithSpriteBody:\n\tNativeCliffBody:\n\t\tSlot: {slot % 100}\n\t\tSourceGrid: true");
				sequences.AppendLine($"terrain.rubberduck.closedcliff{slot}:\n\tidle:\n\t\tFilename: ca|bits/terrain/rubberduck/derived/closed-cliffs/{filename}\n\t\tLength: 1");
			}
			File.WriteAllText(Path.Combine(output, "rules.yaml"), rules.ToString());
			File.WriteAllText(Path.Combine(output, "sequences.yaml"), sequences.ToString());
			File.WriteAllText(Path.Combine(output, "provenance.txt"), provenance.ToString());
		}
	}
}
