// Generated by tools/modular/generate_stock_combat_bindings.py from reviewed stock-combat-baselines.json.
using System.Collections.Generic;

namespace OpenRA.Mods.CA.Modular
{
	public sealed partial class CustomFactionDesign
	{
		static CustomVehicleAssembly StockAssembly(string hull, string actor, string image, string faction, string gear, string motor, string generator, string armor, string carrier, string prerequisites, bool hover)
		{
			var assembly = new CustomVehicleAssembly(hull, actor, image, null, new[] { gear }, new[] { motor }, armor,
				carrier, "original-armament", new[] { "integral-stores" }, new Dictionary<string, string>())
			{
				Faction = faction, PreserveWeaponTemplates = true, PreserveActorGraphics = true, InheritStockWeapons = true,
				StockPrerequisites = prerequisites, NativeHover = hover,
				Summary = carrier == "superheavy-bunker" ? "Battle Fortress + Bunker Module: original passengers, firing ports, machine gun/flak and bunker graphics." : "Original combat assembly: chassis-bound weapons and abilities included in the price."
			};
			assembly.Choices["generator"] = new[] { generator };
			return assembly;
		}

		static CustomVehicleAssembly[] CreateStockCombatAssemblies() => new[]
		{
			StockAssembly("stock-1tnk-hull", "1TNK", "light_tank", "allies", "tracks-standard", "diesel", "baseline-generator", "heavy", "integrated-mount", "weap, vehicles, ~allies, ~!promotion.scout_tank_pdl, ~!promotion.scout_tank.reflector", false),
			StockAssembly("stock-apc-hull", "APC", "apc", "allies", "tracks-standard", "diesel", "baseline-generator", "heavy", "integrated-mount", "tent, ~weap, vehicles, ~!soviet", false),
			StockAssembly("stock-batf-hull", "BATF.Bunker", "batf.bunker", "allies", "tracks-superheavy", "diesel", "baseline-generator", "heavy", "superheavy-bunker", "radar, ~weap, ~promotion.battle_fortress.bunker, ~!upg.batf2", false),
			StockAssembly("stock-chpr-hull", "CHPR", "chpr", "allies", "designer-heavy-tracks", "diesel", "baseline-generator", "heavy", "integrated-mount", "tier3, ~promotion.chrono_prison, ~!promotion.chrono_prison_range, ~!promotion.chrono_prison_aa", false),
			StockAssembly("stock-cryo-hull", "CRYO", "cryo", "allies", "light-tracks", "diesel", "baseline-generator", "light", "integrated-mount", "radar, vehicles, ~allies, ~promotion.cryo_launcher", false),
			StockAssembly("stock-ctnk-hull", "CTNK", "ctnk", "allies", "heavy-wheels", "diesel", "baseline-generator", "heavy", "integrated-mount", "tier3, vehicles, ~allies, ~promotion.chrono_tank, ~!promotion.chrono_tank_pdl, ~!promotion.chrono_tank.reflector", false),
			StockAssembly("stock-ifv-hull", "IFV", "ifv", "allies", "prototype-hover", "diesel", "baseline-generator", "light", "integrated-mount", "infantry.any, vehicles, ~allies", true),
			StockAssembly("stock-rtnk-hull", "RTNK", "mirage", "allies", "tracks-standard", "diesel", "baseline-generator", "heavy", "integrated-mount", "weap, vehicles, ~england, ~!upg.mirage", false),
			StockAssembly("stock-tnkd-hull", "TNKD", "tank_destroyer", "allies", "tracks-standard", "diesel", "baseline-generator", "heavy", "integrated-mount", "vehicles, ~allies, tier2, ~!upg.tank_destroyer", false),
			StockAssembly("stock-gdrn-hull", "GDRN", "gdrn", "gdi", "wheels-light", "diesel-light", "baseline-generator", "light", "mini-turret-mount", "vehicles, ~gdi", false),
			StockAssembly("stock-mdrn-hull", "MDRN", "mdrn", "gdi", "amphibious-micro", "diesel-light", "baseline-generator", "light", "integrated-mount", "radar, vehicles, ~gdi", false),
			StockAssembly("stock-vulc-hull", "VULC", "vulc", "gdi", "tracks-standard", "diesel", "baseline-generator", "heavy", "dual-gatling-turret", "vehicles, ~gdi, tier3, ~promotion.apc_vulcan, ~infantry.any", false),
			StockAssembly("stock-xo-hull", "XO", "xo", "gdi", "scrin-walker-gear", "diesel", "baseline-generator", "light", "integrated-mount", "weap.td, vehicles, ~gdi", false),
			StockAssembly("stock-atmz-hull", "ATMZ", "ATMZ", "scrin", "scrin-hover-gear", "scrin-drive", "scrin-converter", "light", "integrated-mount", "tier3, vehicles, ~traveler, ~!upg.ruiner", true),
			StockAssembly("stock-channeler-hull", "Channeler", "Channeler", "scrin", "prototype-hover", "scrin-drive", "scrin-converter", "heavy", "integrated-mount", "tier2, vehicles, ~scrin, ~!upg.channeler", true),
			StockAssembly("stock-hexapod-hull", "Hexapod", "hexapod", "scrin", "walker-heavy", "scrin-drive", "scrin-converter", "heavy", "integrated-mount", "tier3, ~promotion.hexapod", false),
			StockAssembly("stock-intl-hull", "INTL", "INTL", "scrin", "scrin-hover-gear", "scrin-drive", "scrin-converter", "light", "integrated-mount", "wsph, vehicles, ~scrin, ~!upg.interloper", true),
			StockAssembly("stock-lace-hull", "LACE", "LACE", "scrin", "scrin-hover-gear", "scrin-drive", "scrin-converter", "light", "integrated-mount", "vehicles, ~traveler, ~!upg.lacerator", true),
			StockAssembly("stock-lchr-hull", "LCHR", "LCHR", "scrin", "scrin-hover-gear", "scrin-drive", "scrin-converter", "light", "integrated-mount", "tier2, vehicles, ~scrin, ~!upg.leecher", true),
			StockAssembly("stock-rptp-hull", "RPTP", "RPTP", "scrin", "designer-mk2-legs", "scrin-drive", "scrin-converter", "heavy", "integrated-mount", "tier3, vehicles, ~scrin, ~!upg.reaper", false),
			StockAssembly("stock-ruin-hull", "RUIN", "RUIN", "scrin", "scrin-hover-gear", "scrin-drive", "scrin-converter", "light", "integrated-mount", "tier3, vehicles, ~scrin, ~!upg.ruiner", true),
			StockAssembly("stock-stcr-hull", "STCR", "STCR", "scrin", "prototype-hover", "scrin-drive", "scrin-converter", "light", "integrated-mount", "tier2, vehicles, ~scrin, ~!upg.stormcrawler", true),
			StockAssembly("stock-tpod-hull", "TPOD", "TPOD", "scrin", "designer-mk2-legs", "scrin-drive", "scrin-converter", "heavy", "integrated-mount", "tier3, vehicles, ~traveler, ~!upg.tripod", false),
			StockAssembly("stock-2s3-hull", "2S3", "2s3", "soviet", "tracks-standard", "diesel", "baseline-generator", "heavy", "integrated-mount", "dome, ~promotion.akatsiya", false),
			StockAssembly("stock-btr-hull", "BTR", "btr", "soviet", "wheels-light", "diesel-light", "baseline-generator", "light", "integrated-mount", "barr, vehicles, ~soviet, ~promotion.btr", false),
			StockAssembly("stock-chem-sprayer-hull", "Chem_Sprayer", "chemsprayer", "soviet", "wheels-light", "diesel-light", "baseline-generator", "light", "integrated-mount", "~vehicles.soviet, radar, ~!upg.chem_sprayer", false),
			StockAssembly("stock-dtrk-hull", "DTRK", "dtrk", "soviet", "wheels-light", "diesel-light", "baseline-generator", "light", "integrated-mount", "stek, ~vehicles.soviet", false),
			StockAssembly("stock-devil-tank-hull", "Devil_Tank", "deviltank", "soviet", "tracks-standard", "diesel", "baseline-generator", "heavy", "integrated-mount", "~vehicles.soviet, ~!upg.devil_tank", false),
			StockAssembly("stock-gene-splicer-hull", "Gene_Splicer", "gene_splicer", "soviet", "tracks-superheavy", "diesel", "baseline-generator", "heavy", "integrated-mount", "~promotion.gene_splicer, cloning_vats", false),
			StockAssembly("stock-hq7-hull", "HQ7", "hq7", "soviet", "wheels-light", "diesel-light", "baseline-generator", "light", "integrated-mount", "~vehicles.soviet, radar", false),
			StockAssembly("stock-htk5-hull", "HTK5", "htk5", "soviet", "wheels-light", "diesel-light", "baseline-generator", "light", "integrated-mount", "~vehicles.russia, radar", false),
			StockAssembly("stock-hyena-hull", "Hyena", "hyena", "soviet", "wheels-light", "diesel-light", "baseline-generator", "light", "integrated-mount", "~vehicles.soviet, radar", false),
			StockAssembly("stock-isu-hull", "ISU", "ISU", "soviet", "designer-heavy-tracks", "diesel", "baseline-generator", "heavy", "integrated-mount", "radar, ~vehicles.soviet, ~!upg.isu", false),
			StockAssembly("stock-katy-hull", "KATY", "katy", "soviet", "wheels-light", "diesel-light", "baseline-generator", "light", "integrated-mount", "dome, ~promotion.katyusha", false),
			StockAssembly("stock-nonasvk-hull", "NonaSVK", "nonasvk", "soviet", "wheels-light", "diesel-light", "baseline-generator", "light", "integrated-mount", "vehicles, ~soviet, ~promotion.nona_svk", false),
			StockAssembly("stock-peoples-tank-hull", "Peoples_Tank", "peoplestank", "soviet", "tracks-standard", "diesel", "baseline-generator", "heavy", "integrated-mount", "~vehicles.soviet, radar, ~!upg.peoples_tank", false),
			StockAssembly("stock-qtnk-hull", "QTNK", "qtnk", "soviet", "tracks-standard", "diesel", "baseline-generator", "heavy", "integrated-mount", "tier3, ~vehicles.soviet, ~promotion.general_armaggeddon", false),
			StockAssembly("stock-rice-cooker-hull", "Rice_Cooker", "rice_cooker", "soviet", "tracks-standard", "diesel", "baseline-generator", "heavy", "integrated-mount", "indp, ~promotion.rice_cooker", false),
			StockAssembly("stock-source-of-pollution-hull", "Source_of_Pollution", "Source_of_Pollution", "soviet", "designer-heavy-tracks", "diesel", "baseline-generator", "heavy", "integrated-mount", "radar, ~vehicles.soviet, ~!upg.source_of_pollution", false),
			StockAssembly("stock-ttnk-hull", "TTNK", "ttnk", "soviet", "light-tracks", "diesel", "baseline-generator", "light", "integrated-mount", "~vehicles.soviet, dome, ~!promotion.tesla_arc", false),
			StockAssembly("stock-tsar-tank-hull", "Tsar_Tank", "tsar", "soviet", "tracks-superheavy", "diesel", "baseline-generator", "heavy", "integrated-mount", "radar, ~vehicles.russia, ~promotion.tsar", false),
			StockAssembly("stock-v3rl-hull", "V3RL", "v3rl", "soviet", "wheels-light", "diesel-light", "baseline-generator", "light", "integrated-mount", "tier3, ~vehicles.soviet, radar, ~promotion.v3_launcher", false),
			StockAssembly("stock-apoc-hull", "apoc", "apoc", "soviet", "designer-heavy-tracks", "diesel", "baseline-generator", "heavy", "integrated-mount", "radar, ~vehicles.russia, ~!upg.apocalypse_tank", false),
			StockAssembly("stock-kims-wheel-hull", "kims_wheel", "kimswheel", "soviet", "wheels-light", "diesel-light", "baseline-generator", "light", "integrated-mount", "~vehicles.soviet", false),
		};
	}
}
